### ISSUE TITLE
M2L3. Добавить тесты для Репозитория

### ISSUE THREAD

**Issue by SShliakhin** [Select-IOS-Team/ToDoListCleanSwift#31]
1. Протестировать  IRepository - создать новый класс и подписать под этот протокол
2. Протестировать repository.getAllTasks()
    - количество записей
    -  наличие записей в репозитории по конкретному свойству
3. Протестировать repository.getAllTasks() на кастомном репозитории
    - количество записей
    - наличие записей по ссылке

Ветка: feature/M2L3-31-RepositoryTests

**Comment by Blissfulman** [comment]
Выполнено
