### ISSUE TITLE
M2L3. Добавить тесты для LoginWorker

### ISSUE THREAD

**Issue by SShliakhin** [Select-IOS-Team/ToDoListCleanSwift#35]
## Описание задачи

1. Надо проверить с корректными данными на выходе должны получить true - `LoginDTO(success: 1, login: login, lastLoginDate: Date())`
2. Надо проверить с неправильными данными на выходе должны получить false - `LoginDTO(success: 0, login: login, lastLoginDate: Date())`
3. Для этого создать шаблоны для корректного и неверного ответов и будем сравнивать с выходом

Ветка: feature/M2L3-35-LoginWorkerTests

**Comment by Blissfulman** [comment]
Выполнено
